name: Build
on: push
jobs:
  run_file:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
       python-version: '3.x'
       architecture: 'x64'
    - run: python calculator.py
